config/routes.rb
Rails.application.routes.draw do

#管理者側
# URL /admin/sign_in...
#管理者側のコントローラーがどこに存在するかを指定
#新規登録、パスワード変更はしないためskip オプションで削除
#加えてapp/views/admin/shared/_links.html.erbの余分な記述を削除
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: 'admin/sessions',
  }

  #会員側
  # URL /end_users/sign_in...
  #会員側のコントローラーがどこに存在するかを指定
  devise_for :end_users, controllers: {
    sessions: 'public/sessions',
    registrations: 'public/registrations',
  }

  devise_scope :end_user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  #URLはadminをつけて、ファイル構成も指定
  namespace :admin do
    #カテゴリー
    resources :categories, only: [:index, :create, :destroy,]
    #本
    resources :books, only: [:index, :show]
    #レビュー
    resources :reviews, only: [:index, :show, :destroy,]
    #ユーザー
    resources :end_users, only: [:index, :show, :destroy,]

  end

  #URLはそのまま、ファイル構成だけ指定のパス
  scope module: :public do

    get root to: 'homes#top'
    get 'searchs/search_result', to: 'searchs#search_result', as: 'search_result'
    #カテゴリー
    resources :categories, only: [:index, :show]
    #出品
    resources :sales
    #先にdestroy_allを置く
    delete 'cart_items/destroy_all', to: 'cart_items#destroy_all', as: 'destroy_all_cart_items'
    #カート内商品
    resources :cart_items, only: [:index, :create, :destroy]
    #注文
    get 'orders/order_confirm', to: 'orders#order_404'
    post 'orders/order_confirm', to: 'orders#order_confirm', as: 'order_confirm'
    get 'orders/thanks', to: 'orders#thanks', as: 'thanks'
    resources :orders, only: [:index, :new, :create, :show, :update]

    #住所
    resources :addresses, only: [:index, :create, :destroy, :edit, :update]
    get 'end_users/mypage', to: 'end_users#mypage', as: 'mypage'
    get 'end_users/unsubscribe', to: 'end_users#unsubscribe', as: 'confirm_unsubscribe'
    patch 'end_users/withdraw', to: 'end_users#withdraw', as: 'withdraw_end_user'
    #ユーザー
    resources :end_users, only: [:index, :show, :edit, :update] do
      member do
        #フォローフォロワー
        get :follows, :followers
      end
      resource :relationships, only: [:create, :destroy]
    end
    #本
    resources :books, only: [:index, :destroy, :create, :show] do
      get 'rakuten_result', to: 'books#rakuten_result', as: 'rakuten_result'
    end
    #レビュー
    resources :reviews, only: [:index, :create, :show, :edit, :update, :destroy] do
      #イイね機能(会員1人につき1イイね)
      resource :favorites, only: [:create, :destroy]
      #コメント機能
      resources :review_comments, only: [:create, :destroy]
      ##下書き機能(下書きページのためurlがつかない)
      collection do
        get 'review_confirm', as: 'review_confirm'
      end
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admin/reviews_controller.rb
class Admin::ReviewsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @reviews = Review.page(params[:page])
  end

  def show
    @review = Review.find(params[:id])
    @index = params[:index]
  end

  def destroy
    review = Review.find(params[:id ])
    review.destroy
    redirect_to admin_reviews_path
  end

end

app/helpers/admin/reviews_helper.rb
module Admin::ReviewsHelper
end

app/views/admin/reviews/index.html.erb
<div class="container">
  <h2 class= "col-md-6 col-sm-12 py-5 mx-auto">レビュー一覧</h2>
    <div class= "row w-90 mx-auto mt-1 bg-light shadow-lg">
      <div class="h6 col-md-2 col-sm-12"><strong>投稿本</strong></div>
      <div class="h6 col-md-2 col-sm-12"><strong>ユーザー</strong></div>
      <div class="h6 col-md-8 col-sm-12"><strong>内容</strong></div>
    </div>
    <% if @reviews.present? %>
      <% @reviews.each do |review| %>
        <div class= "row w-90 mx-auto bg-light">
          <div class="col-md-2 col-sm-12">
            <%= link_to (image_tag(review.book.medium_image_url)), review.book.item_url %>
          </div>
          <div class="col-md-2 col-sm-12">
            <%= image_tag review.end_user.get_profile_image("100x100"), class:"mt-3 rounded-circle"; %>
            <p><%= review.end_user.last_name %><%= review.end_user.first_name %></p>
          </div>
          <div class="ccol-md-8 col-sm-12">
            <p><%= review.book.title %></p>
            <p><%= review.heading %></p>
            <p><%= link_to "詳細", admin_review_path(review), class: "btn btn-sm btn-info" %></p>
          </div>
        </div>
      <% end %>
    <% else %>
      <p>ご登録のレビューはありません</p>
    <% end %>

  <%= paginate @reviews %>
</div>

app/views/admin/reviews/show.html.erb
<div class="container">
  <h2 class= "col-md-6 col-sm-12 py-5 mx-auto">詳細</h2>
  <div class= "row w-80 mx-auto my-2 bg-light shadow-lg">
    <div class="col-md-2 col-sm-12 px-0">
      <%= link_to (image_tag(@review.book['large_image_url'])), @review.book['item_url'] %>
      <div id="score_<%= @index %>"><%= render 'public/reviews/score', review: @review, index: @index %></div>
      <%= @review.score %>
    </div>
    <div class="col-md-2 col-sm-12 px-0">
      <h5 class="title col-12 py-1">タイトル</h5>
      <h5 class="title col-12 py-1">著者</h5>
      <h5 class="title col-12 py-1">出版社</h5>
    </div>
    <div class="col-md-8 col-sm-12">
      <p><%= @review.book.title %></p>
      <p><%= @review.book.author %></p>
      <p><%= @review.book.publisher_name %></p>
    </div>
  </div>
  <div class="row w-80 mx-auto my-2 bg-light shadow-lg">
    <div class="col">
      <h5 class="title col-12">テーマ</h5>
      <p><%= @review.heading %></p>
      <h5 class="title col-12">批評</h5></h5>
      <p><%= @review.blog %></p>
    </div>
  </div>
  <div>
    <%= link_to "このレビューを削除する", admin_review_path(@review),
    method: :delete, data: {confirm: "本当に削除しますか？"},class: "btn btn-lg btn-danger" %>
  </div>
</div>