config/routes.rb
Rails.application.routes.draw do

#管理者側
# URL /admin/sign_in...
#管理者側のコントローラーがどこに存在するかを指定
#新規登録、パスワード変更はしないためskip オプションで削除
#加えてapp/views/admin/shared/_links.html.erbの余分な記述を削除
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: 'admin/sessions',
  }

  #会員側
  # URL /end_users/sign_in...
  #会員側のコントローラーがどこに存在するかを指定
  devise_for :end_users, controllers: {
    sessions: 'public/sessions',
    registrations: 'public/registrations',
  }

  devise_scope :end_user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  #URLはadminをつけて、ファイル構成も指定
  namespace :admin do
    #カテゴリー
    resources :categories, only: [:index, :create, :destroy,]
    #本
    resources :books, only: [:index, :show]
    #レビュー
    resources :reviews, only: [:index, :show, :destroy,]
    #ユーザー
    resources :end_users, only: [:index, :show, :destroy,]

  end

  #URLはそのまま、ファイル構成だけ指定のパス
  scope module: :public do

    get root to: 'homes#top'
    get 'searchs/search_result', to: 'searchs#search_result', as: 'search_result'
    #カテゴリー
    resources :categories, only: [:index, :show]
    #出品
    resources :sales
    #先にdestroy_allを置く
    delete 'cart_items/destroy_all', to: 'cart_items#destroy_all', as: 'destroy_all_cart_items'
    #カート内商品
    resources :cart_items, only: [:index, :create, :destroy]
    #注文
    get 'orders/order_confirm', to: 'orders#order_404'
    post 'orders/order_confirm', to: 'orders#order_confirm', as: 'order_confirm'
    get 'orders/thanks', to: 'orders#thanks', as: 'thanks'
    resources :orders, only: [:index, :new, :create, :show, :update]

    #住所
    resources :addresses, only: [:index, :create, :destroy, :edit, :update]
    get 'end_users/mypage', to: 'end_users#mypage', as: 'mypage'
    get 'end_users/unsubscribe', to: 'end_users#unsubscribe', as: 'confirm_unsubscribe'
    patch 'end_users/withdraw', to: 'end_users#withdraw', as: 'withdraw_end_user'
    #ユーザー
    resources :end_users, only: [:index, :show, :edit, :update] do
      member do
        #フォローフォロワー
        get :follows, :followers
      end
      resource :relationships, only: [:create, :destroy]
    end
    #本
    resources :books, only: [:index, :destroy, :create, :show] do
      get 'rakuten_result', to: 'books#rakuten_result', as: 'rakuten_result'
    end
    #レビュー
    resources :reviews, only: [:index, :create, :show, :edit, :update, :destroy] do
      #イイね機能(会員1人につき1イイね)
      resource :favorites, only: [:create, :destroy]
      #コメント機能
      resources :review_comments, only: [:create, :destroy]
      ##下書き機能(下書きページのためurlがつかない)
      collection do
        get 'review_confirm', as: 'review_confirm'
      end
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/end_user.rb
class EndUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :review_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_end_users, through: :favorites, source: :review
  has_many :sales, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
  #外部キーも指定
  #has_many :relationships, dependent: :destroy
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  #自分がフォローしている人=自分にフォロされた人(source)
  has_many :following_end_user, through: :follower, source: :followed
  #自分がフォローされている人=自分をフォロした人(source)
  has_many :follower_end_user, through: :followed, source: :follower


  def following?(end_user)
    following_end_user.include?(end_user)
  end

  #ゲストログイン用にアカウントを用意

  def self.guest
    find_or_create_by!(last_name: 'ゲスト', first_name: 'ユーザー', email: 'guest@example.com') do |end_user|
      end_user.password = SecureRandom.urlsafe_base64
      end_user.last_name = 'ゲスト'
      end_user.first_name = 'ユーザー'
    end
  end

  #profile_imageカラムが追加されたように扱える
  has_one_attached :profile_image
  #拡張子を制限してエラーが出ないようにしている
  validate :profile_image_content_type, if: :was_attached?

  def profile_image_content_type
    extension = ['image/png', 'image/jpg', 'image/jpeg']
    errors.add(:profile_image, "の拡張子が間違ってます") unless profile_image.content_type.in?(extension)
  end

  def was_attached?
    self.profile_image.attached?
  end
  #profile_imageが設定されない時、no-image.jpgをデフォルト画像としてActiveStorageに格納、その後表示。
  #サイズの変更も行う。
  def get_profile_image(size)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no-image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end

    profile_image.variant(resize: size).processed
  end
end

app/controllers/admin/end_users_controller.rb
class Admin::EndUsersController < ApplicationController
  before_action :authenticate_admin!
  def index
    @end_users = EndUser.page(params[:page])
  end

  def destroy
    end_user = EndUser.find(params[:id])
    end_user.destroy
    redirect_to admin_end_users_path

  end

  def show
    @end_user = EndUser.find(params[:id])
    #複数の本＝会員の本全部
    @reviews = @end_user.reviews
  end

end

app/helpers/admin/end_users_helper.rb
module Admin::EndUsersHelper
end

app/views/admin/end_users/index.html.erb
<div class="container">
  <div class="row mx-auto w-80">
    <h2 class= "col-md-6 col-sm-12 py-5 mx-auto">ユーザー一覧</h2>
    <div class= "hover col-12 bg-light">
      <div class ="row">
        <div class= "col-md-1 col-sm-12 py-2">会員ID</div>
        <div class= "col-md-2 col-sm-12 py-2">イメージ</div>
        <div class= "col-md-2 col-sm-12 py-2">氏名</div>
        <div class= "col-md-2 col-sm-12 py-2">フリガナ</div>
        <div class= "col-md-2 col-sm-12 py-2">会員ステータス</div>
      </div>
      <% if @end_users.present? %>
        <% @end_users.each do |end_user| %>
          <div class="row">
            <div class="col-md-1 col-sm-12"><%= end_user.id %></div>
            <div class="col-md-2 col-sm-12"><%= image_tag end_user.get_profile_image("100x100") %></div>
            <div class="col-md-2 col-sm-12"><%= end_user.last_name %><%= end_user.first_name %></div>
            <div class="col-md-2 col-sm-12"><%= end_user.last_name_kana %><%= end_user.first_name_kana %></div>
            <div class="col-md-2 col-sm-12"><%= end_user.is_deleted ? "退会" : "有効" %></div>
            <div class="col-md-2 col-sm-12">
              <%= link_to "詳細", admin_end_user_path(end_user),
              class: "btn btn-sm px-4 btn-info" %>
            </div>
          </div>
        <% end %>
      <% else %>
        <p>ユーザーはおりません</p>
      <% end %>
    </div>
  </div>
  <%= paginate @end_users %>
</div>

app/views/admin/end_users/show.html.erb
<div class= "container">
  <div class ="row">
    <div class = "card-list-container col-12">
       <h2 class="text-dark mt-5">マイページ</h2>
      <div class= "card mx-auto mt-1 shadow-lg">
        <div class= "card-body">
          <div class = "row">
            <div class="col-md-2 col-sm-12">
              <%= image_tag @end_user.get_profile_image("100x100") %>
            </div>
            <div class="col-10">
              <div class= "profile">
                <div class="row">
                  <div class="col-md-3 col-sm-12 py-1">氏名</div>
                  <div class="col-md-3 col-sm-12 py-1">フリガナ</div>
                  <div class="col-md-3 col-sm-12 py-1">ニックネーム</div>
                  <div class="col-md-3 col-sm-12 py-1">ステータス</div>
                </div>
                <div class="row">
                  <div class="col-md-3 col-sm-12 py-1"><%= @end_user.last_name %><%= @end_user.first_name %></div>
                  <div class="col-md-3 col-sm-12 py-1"><%=@end_user.last_name_kana %><%= @end_user.first_name_kana %></div>
                  <div class="col-md-3 col-sm-12 py-1"><%= @end_user.nickname %> </div>
                  <div class="col-md-3 col-sm-12 py-1"><%= @end_user.is_deleted ? "退会" : "有効" %></div>
                </div>
                <div class="row">
                  <div class="col-md-3 col-sm-12 py-1">メールアドレス</div>
                  <div class="col-md-3 col-sm-12 py-1">電話番号</div>
                  <div class="col-md-3 col-sm-12 py-1">郵便番号</div>
                  <div class="col-md-3 col-sm-12 py-1">住所</div>
                </div>
                <div class="row">
                  <div class="col-md-3 col-sm-12 py-1"><%= @end_user.email %></div>
                  <div class="col-md-3 col-sm-12 py-1"><%= @end_user.telephone_number %></div>
                  <div class="col-md-3 col-sm-12 py-1"><%= @end_user.postal_code %></div>
                  <div class="col-md-3 col-sm-12 py-1"><%= @end_user.address %></div>
                </div>
              </div>
              <div class="row">
                <div class= "col-12 py-2">
                  <h4>プロフィール</h4>
                  <div class="col-12"><%= @end_user.introduction %></div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <p class ="col-md-4 col-sm-12"><%= link_to "アカウント削除", admin_end_user_path(@end_user), method: :delete, data: { confirm: "本当に削除しますか？"}, class: "btn btn-lg px-4 btn-danger" %></p>
      </div>
    </div>
  </div>
</div>