config/routes.rb
Rails.application.routes.draw do

#管理者側
# URL /admin/sign_in...
#管理者側のコントローラーがどこに存在するかを指定
#新規登録、パスワード変更はしないためskip オプションで削除
#加えてapp/views/admin/shared/_links.html.erbの余分な記述を削除
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: 'admin/sessions',
  }

  #会員側
  # URL /end_users/sign_in...
  #会員側のコントローラーがどこに存在するかを指定
  devise_for :end_users, controllers: {
    sessions: 'public/sessions',
    registrations: 'public/registrations',
  }

  devise_scope :end_user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  #URLはadminをつけて、ファイル構成も指定
  namespace :admin do
    #カテゴリー
    resources :categories, only: [:index, :create, :destroy,]
    #本
    resources :books, only: [:index, :show]
    #レビュー
    resources :reviews, only: [:index, :show, :destroy,]
    #ユーザー
    resources :end_users, only: [:index, :show, :destroy,]

  end

  #URLはそのまま、ファイル構成だけ指定のパス
  scope module: :public do

    get root to: 'homes#top'
    get 'searchs/search_result', to: 'searchs#search_result', as: 'search_result'
    #カテゴリー
    resources :categories, only: [:index, :show]
    #出品
    resources :sales
    #先にdestroy_allを置く
    delete 'cart_items/destroy_all', to: 'cart_items#destroy_all', as: 'destroy_all_cart_items'
    #カート内商品
    resources :cart_items, only: [:index, :create, :destroy]
    #注文
    get 'orders/order_confirm', to: 'orders#order_404'
    post 'orders/order_confirm', to: 'orders#order_confirm', as: 'order_confirm'
    get 'orders/thanks', to: 'orders#thanks', as: 'thanks'
    resources :orders, only: [:index, :new, :create, :show, :update]

    #住所
    resources :addresses, only: [:index, :create, :destroy, :edit, :update]
    get 'end_users/mypage', to: 'end_users#mypage', as: 'mypage'
    get 'end_users/unsubscribe', to: 'end_users#unsubscribe', as: 'confirm_unsubscribe'
    patch 'end_users/withdraw', to: 'end_users#withdraw', as: 'withdraw_end_user'
    #ユーザー
    resources :end_users, only: [:index, :show, :edit, :update] do
      member do
        #フォローフォロワー
        get :follows, :followers
      end
      resource :relationships, only: [:create, :destroy]
    end
    #本
    resources :books, only: [:index, :destroy, :create, :show] do
      get 'rakuten_result', to: 'books#rakuten_result', as: 'rakuten_result'
    end
    #レビュー
    resources :reviews, only: [:index, :create, :show, :edit, :update, :destroy] do
      #イイね機能(会員1人につき1イイね)
      resource :favorites, only: [:create, :destroy]
      #コメント機能
      resources :review_comments, only: [:create, :destroy]
      ##下書き機能(下書きページのためurlがつかない)
      collection do
        get 'review_confirm', as: 'review_confirm'
      end
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class= "alert alert-<%= message_type %>" id="alert">
    <a href= "#" class"close" data-dismiss = "alert"><i class="far fa-times-circle"></i></a>
    <%= message %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class= "bg-dark text-white pt-5 pd-4">
  <div class= "container">
    <div class= "row no-gutters">
      <div class= "col-md-6 col-sm-12 px-2">
        <p>
          本を考察して発信したいと思ったら…<br>
          本好きな人の集まるサイトです。<br>
        </p>
      </div>
      <div class= "col-md-6 col-sm-12 px-4">
        <h6>参照リンク</h6>
        <ul>
          <li>
            <a class="navbar-brand p-3" href="https://books.rakuten.co.jp/">
              楽天ブックス<br>
              :https://books.rakuten.co.jp/
            </a>
          </li>
        </ul>
        <ul>
          <li>
            <%= link_to "管理者ページはこちら", new_admin_session_path ,class: "navbar-brand p-3" %>
          </li>
        </ul>

      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="shadow-sm">
  <nav class= "navbar navbar-expand-lg navbar-light" >

       <a class="navbar-brand" href="/"><%= image_tag asset_path('header_logo'), size: "300x100" %></a>
      <button class= "navbar-toggler" type="button" data-toggle= "collapse" data-target= "#navbarNavDropdown"
              aria-controls= "navbarNavDropdown" aria-expanded= "false" aria-label"Toggle navigation">
        <span class= "navbar-toggler-icon"></span>
      </button>

      <div class= "collapse navbar-collapse" id = "navbarNavDropdown">
        <ul class = "navbar-nav ml-auto">
          <% if admin_signed_in? %>

            <li class= "nav-item active">
              <%= link_to admin_end_users_path, class: 'nav-link text-dark' do %>
                <i class="fas fa-users"></i>ユーザー
              <% end %>
            </li>
            <li class= "nav-item active">
              <%= link_to admin_reviews_path, class: 'nav-link text-dark' do %>
                <i class="fas fa-edit"></i>レビュー
              <% end %>
            </li>
            <li class= "nav-item active">
              <%= link_to admin_categories_path, class: 'nav-link text-dark' do %>
                <i class="fas fa-tags"></i>カテゴリー
              <% end %>
            </li>
            <li class= "nav-item active">
              <%= link_to destroy_admin_session_path, method: :get, class: 'nav-link text-dark' do %>
                <i class="fas fa-sign-out-alt"></i>ログアウト
              <% end %>
            </li>

          <% elsif end_user_signed_in? %>

            <li class= "nav-item active">
              <%= link_to root_path, class: 'nav-link text-dark' do %>
                <i class="fas fa-home"></i>ホーム
              <% end %>
            </li>
            <li class= "nav-item active">
              <%= link_to mypage_path, class: 'nav-link text-dark' do %>
                <i class="far fa-user-circle"></i>マイページ
              <% end %>
            </li>
            <li class= "nav-item active">
              <%= link_to reviews_path, class: 'nav-link text-dark' do %>
                <i class="fas fa-edit"></i>レビュー
              <% end %>
            </li>
             <li class= "nav-item active">
              <%= link_to review_confirm_reviews_path, class: 'nav-link text-dark' do %>
                <i class="far fa-edit"></i>下書き
              <% end %>
            </li>
            <li class= "nav-item active">
              <%= link_to end_users_path, class: 'nav-link text-dark' do%>
                <i class="fas fa-users"></i>ユーザー
              <% end %>
            </li>
            <li class= "nav-item active">
              <%= link_to new_sale_path, class: 'nav-link text-dark' do %>
                <i class="fas fa-store"></i>出品
              <% end %>
            </li>
            <li class= "nav-item active">
              <%= link_to sales_path, class: 'nav-link text-dark' do %>
                <i class="fas fa-shopping-cart"></i>購入
              <% end %>
            </li>
            <!--エラーが出たためdeleteからgetに修正-->
            <li class= "nav-item active">
              <%= link_to destroy_end_user_session_path, class: 'nav-link text-dark' do %>
                <i class="fas fa-sign-out-alt"></i>ログアウト
              <% end %>
            </li>

          <% else %>
            <li class= "nav-item active">
              <%= link_to root_path, class: 'nav-link text-dark' do %>
                <i class="fas fa-home"></i>ホーム
              <% end %>
            </li>
            <li class= "nav-item active">
              <%= link_to new_end_user_registration_path, class: 'nav-link text-dark' do %>
                <i class="fas fa-user-plus"></i>新規登録
              <% end %>
            </li>
            <li class= "nav-item active">
              <%= link_to new_end_user_session_path, class: 'nav-link text-dark' do %>
                <i class="fas fa-sign-in-alt"></i>ログイン
              <% end %>
            </li>
            <li class= "nav-item active">
              <%= link_to users_guest_sign_in_path, method: :post, class: 'nav-link text-dark' do %>
                 <i class="fas fa-sign-in-alt"></i>ログイン（ゲスト用）
              <% end %>
            </li>

          <% end %>
        </ul>
      </div>

  </nav>

</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SecondBookstore</title>
    <meta name="viewport" content="width=device-width,initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'layouts/header' %>
    <div class="main-container w-100 px-0">
      <%= render 'layouts/flash_messages' %>
      <%= yield %>
      <span id = "back">
        <a href="">
          <%= image_tag asset_path('arrow.png'), data: {"turbolinks"=> false}, class: "arrow" %>
        </a>
      </span>
    </div>
    <%= render "layouts/footer" %>
  </body>
</html>